[firebase]
type = "service_account"
project_id = "xper-01"
private_key_id = "4e4ee681fbe4f0389490d35f6644661c96f352cc"

# Paste the PEM exactly, WITHOUT quotes around it, and WITH real new lines.
# Do NOT include \n sequences here.
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXrzI+xVePXyv8
So1NysOLwXI8cvDIUn3JHUuTINyj+io2fxMqYrbQoB1olKND8iYfXMI6sQZH5Efn
ncfY615dihD9ih6JjHn8S60A8S1m3VTgkXu82eYkRRgWDwNx7k+KIoNO0Ez50lpO
5qbSDldeLch1QgaEFy64avXZIBJQ8XMMqT8tZDsAi1DVzmmXzesCY/OCh7cnDAmt
Jrpjh1IkCI8dm7Yqi3r1KOeJzthx5AQwzgngwxuXIwBSRgHfWFUh+KxQmQ1qG8vf
Ce5QeVs6mvAPIqgVnnc3Maqd1ZvmGEndSqY6rvTo4eaVLWFYz0sVbSg8XYsY+iK6
st5GFsrJAgMBAAECggEAPTVQXoT1dNAO9QGZOS7mMJac2y/JSigy3yyrolzMkNJx
QVbtsvUhqXIO9ntcG++vxu21hx9ux18u0rmxmcst1ADXEoSsZt+RTLqTJbXL6ym7
qSFQSsdRqxBapgPrt9zoAK0Ls4Wkmq8KBuMpC2qbe7Qlc7VhkQHdNePQ0iXqXMKq
xot6aLJSkcDklVI2OnrCKiIJ566c3ydDU9xwjg5dSuLgeZN3gqEavQy8QN8Noh3r
7zMObupfNSMmq97I/Glbjr9/XJWC8tuSTDkmY9/2BzsmV0QauNSr8yzYeJdLHoiQ
97REJBBPkXcFGI6m/Fza305re1Af75Fw2IX3J3Ry+wKBgQD/949jskl2Jj4zVm3i
RDR5ICY8kGIfEZmMtDYl7UVM5rCILJu8TNAyCfmbYEA9m1Szaq6NzR1q5Itosjvm
TDPRsispH2O4u6H9tH0IaYqgZNMTcwRkwxLyDDKjcaekixvcU8GLlkIVQZSoXP9L
kkvJH14JE/nIKK5Cq3xpWeLVGwKBgQDXtk7Usw3lO5iy2M0hV6V3WYrik5PHUCv8
hRm67xWQJCG6Vd/M2s/Z1GsmAy1g/YGAiQWzrBJYjJ/lGwM4dPyVOBVHggydY0CT
u0yTIq++nF3HAe2wI5Tx7j/JyJbiNWR7IgXeO2VCkZR+kVKdlw5Dzhw+A8LBDN3N
Ijef0Gkx6wKBgETkdZRovPruyhj5LzQSFWlwbLoqRi6EhyZmrphAp0FOab8M+pGQ
vwxowOS/4Cp0rzRnBzolNcC6aIcySYrvgZbz9EfqKeXjonLtbCWiemw3FtSKRWl1
U5kQDWUORwezZTlE1bfjJkAgWYmDFjdZ1cn5Bk89MCJeSKCrFR4p0jJ3AoGBAJPX
ol3LPonO99AUITtp68FKAJNb3BvtycfvnXvuYxQAf5FLS/EGQxCjsrBB2zcvaDOl
NeA33fcMooYOpn1qSLco0gTJkEXKgbb+1vO9AUCdwPQlUTe4m1vZE6UDss3lFDIE
VotCoBso1eKNTVcu8ZrtR5QFVdSkMdxnSEJjP8XzAoGAUX6wOplKd+13BKfWg05F
9NXyLKrwxpsA+EAMVeAJv/qUs6BBeM2gVgEhLEbSK6xJ52nr1PNxGG2A/uKARbBn
6cbTmOXD+zT3Y80EWIVsvXB7stTkaZFZNBjwZsvwaWz/kil7UhiNYy4rvMSRy9Yq
L2rUNvRP5HkX75tQFuXUvHM=
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@xper-01.iam.gserviceaccount.com"
client_id = "115811453923394945166"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40xper-01.iam.gserviceaccount.com"
universe_domain = "googleapis.com"